### ISSUE TITLE
Garbage collection

### ISSUE THREAD

**Issue by rohan221102** [rintolang/rinto#12]
Garbage collection implementation for rinto!! This is the idea that I have for the implementation.

Garbage collection is enabled by default, but can be disabled in the header with

`#garbage -disabled`

What do you think about this approach! I feel like doing it the other way around would make it inconvenient for people initially starting out with the language.

**Comment by zeim839** [comment]
The first few versions of rinto are unlikely to have dynamic memory allocation, so garbage collection wont be needed (at least in the foreseable future). I'm also not sure whether toggling garbage collection on/off would even be feasible.

That said, I'm still open to implementing the idea in the future. We should make some sort of todo list (maybe a pinned discussion issue?) to keep track of ideas.
